version: '3.3'

services:
    db:
      image: postgres
      restart: always
      container_name: postgres
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      ports:
        - 5432:5432
      volumes:
        - db-data:/var/lib/postgresql/data
      networks:
        - asvsp_network

    pgadmin:
      image: dpage/pgadmin4
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: andrea.saboc@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 123456
      networks:
        - asvsp_network

    metabase:
      volumes:
        - metabase-data:/metabase-data
      environment:
        - MB_DB_FILE=/metabase-data/metabase.db
        - MB_DB_TYPE=postgres
        - MB_DB_DBNAME=postgres
        - MB_DB_PORT=5432
        - MB_DB_USER=postgres
        - MB_DB_PASS=postgres
        - MB_DB_HOST=db
        - PGDATA= /var/lib/postgresql/data/init/
      ports:
        - 3000:3000
      image: metabase/metabase
      restart: always
      depends_on:
        - db
      networks:
        - asvsp_network

networks:
  asvsp_network:
    external: true

volumes:
  db-data:
  metabase-data: