version: '3.0'

services:
  producer:
    build: 
      args:
        - PYTHON_PRODUCER_VERSION=3.7-slim
      context: ../Producer/Real
    container_name: kafka_producer_1
    restart: on-failure
    environment:
      - KAFKA_BROKER="kafka1:19092"
      - KAFKA_TOPIC="chicago-traffic"
      - DATASET_API_LINK="https://data.cityofchicago.org/resource/n4j6-wkkf.json"
    networks:
      - asvsp_network
    command: python3 ../Producer/Real/producer.py

networks:
  asvsp_network:
    external: true